### ISSUE TITLE
Shaderbuilder on MacOS

### ISSUE THREAD

**Issue by vibber** [satoruhiga/TouchDesigner-ShaderBuilder#2]
Hi there I'm trying out your component and I'm having some problems. I guess they are down to differences between Windows and OSX.
Feel free to get me to test things for you

Here's what happens:

Generator outputs

=============

Vertex Shader Compile Results: 
ERROR: </project1/ShaderBuilder/glsl_common>:93: '=' : syntax error: syntax error

=============

=============

=============

Pixel Shader Compile Results: 
ERROR: </project1/ShaderBuilder/glsl_common>:93: '=' : syntax error: syntax error

=============

Then when I try to change the offending line by simply going:

vec3 blend_normal(vec3 n1, vec3 n2, float mix) {

Then I get this that I don't know how to fix:

=============

Vertex Shader Compile Results: 
ERROR: <glsl_struct>:8: Interpolation qualifiers 'flat' not allowed in struct field context
ERROR: 0:222: Use of undeclared type 'Geometry'
ERROR: 0:222: Use of undeclared type 'Geometry'
ERROR: 0:223: Use of undeclared identifier 'geom'
ERROR: 0:224: Use of undeclared identifier 'geom'
ERROR: 0:225: Use of undeclared identifier 'geom'
ERROR: 0:226: Use of undeclared identifier 'geom'
ERROR: 0:227: Use of undeclared identifier 'geom'
ERROR: 0:228: Use of undeclared identifier 'geom'
ERROR: 0:229: Use of undeclared identifier 'geom'
ERROR: 0:240: Use of undeclared identifier 'geom'
ERROR: 0:240: Use of undeclared identifier 'geom'
ERROR: 0:241: Use of undeclared identifier 'geom'
ERROR: 0:241: Use of undeclared identifier 'geom'
ERROR: 0:249: Use of undeclared identifier 'geom'
ERROR: 0:255: Use of undeclared identifier 'geom'
ERROR: 0:257: Use of undeclared identifier 'geom'
ERROR: 0:258: Use of undeclared identifier 'geom'
ERROR: 0:259: Use of undeclared identifier 'geom'
ERROR: 0:260: Use of undeclared identifier 'geom'
ERROR: 0:261: Use of undeclared identifier 'geom'
ERROR: 0:262: Use of undeclared identifier 'geom'
ERROR: 0:263: Use of undeclared identifier 'geom'

=============

=============

=============

Pixel Shader Compile Results: 
ERROR: <glsl_struct>:8: Interpolation qualifiers 'flat' not allowed in struct field context
ERROR: 0:184: Use of undeclared type 'Geometry'
ERROR: 0:184: Use of undeclared type 'Geometry'
ERROR: 0:185: Use of undeclared identifier 'geom'
ERROR: 0:186: Use of undeclared identifier 'geom'
ERROR: 0:187: Use of undeclared identifier 'geom'
ERROR: 0:188: Use of undeclared identifier 'geom'
ERROR: 0:189: Use of undeclared identifier 'geom'
ERROR: 0:190: Use of undeclared identifier 'geom'
ERROR: 0:191: Use of undeclared identifier 'geom'
ERROR: 0:203: Use of undeclared identifier 'geom'
ERROR: 0:204: Use of undeclared identifier 'normalMap'
ERROR: 0:206: Use of undeclared identifier 'norm'
ERROR: 0:213: No matching function for call to blend_normal(vec3, vec3)
ERROR: 0:216: Use of undeclared identifier 'geom'
ERROR: 0:224: Use of undeclared identifier 'geom'
ERROR: 0:237: Use of undeclared identifier 'geom'
ERROR: 0:239: Use of undeclared identifier 'uv'
ERROR: 0:240: Use of undeclared identifier 'baseColor'
ERROR: 0:241: Use of undeclared identifier 'geom'
ERROR: 0:241: Use of undeclared identifier 'baseColor'
ERROR: 0:243: Use of undeclared identifier 'uv'
ERROR: 0:244: Use of undeclared identifier 'param'
ERROR: 0:245: Use of undeclared identifier 'param'
ERROR: 0:246: Use of undeclared identifier 'param'
ERROR: 0:247: Use of undeclared identifier 'param'
ERROR: 0:249: Use of undeclared identifier 'uv'
ERROR: 0:250: Use of undeclared identifier 'emission'
ERROR: 0:276: Use of undeclared identifier 'geom'
ERROR: 0:277: Use of undeclared identifier 'geom'
ERROR: 0:277: Use of undeclared identifier 'geom'
ERROR: 0:280: Use of undeclared identifier 'geom'
ERROR: 0:283: Use of undeclared identifier 'geom'
ERROR: 0:283: Use of undeclared identifier 'V'
ERROR: 0:283: Use of undeclared identifier 'geom'
ERROR: 0:285: Use of undeclared identifier 'geom'

=============

**Comment by satoruhiga** [comment]
OK, I will check about it.

but It maybe take some week. I'm focus on my project now. sorry about it...

**Comment by satoruhiga** [comment]
It Fixed!

**Comment by vibber** [comment]
great. Thanx.
